version: "3.2"
services:
    ganache:
        image: trufflesuite/ganache-cli:v6.4.1
    runner:
        image: node:8-jessie
        user: ${CURRENT_UID}
        working_dir: /home/node
        volumes:
            - ./:/home/node
        depends_on:
            - ganache
